services:

  mongodb:
    image: mongo:8

    restart: unless-stopped

    volumes:
      - mongo-data:/data/db

  backend:
    image: bodikechaithali/onlinejudge-backend:latest

    restart: unless-stopped

    env_file:
      - ./backend/.env

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - mongodb

  frontend:
    image: bodikechaithali/onlinejudge-frontend:latest

    restart: unless-stopped

    ports:
      - "80:5173"

    depends_on:
      - backend

volumes:
  mongo-data: